name: fccwilmington
favicon: null
layout_spectrum: 0.006432750262320042
typography_spectrum: 0.46490564686246216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.20692546805366874
  lightness: 0.2598951975814998
  saturation: 0.985558140091598
  rhythmicContrast: 0.026268701069056988
purpose: []
